// <auto-generated />
namespace truYum1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class truYum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(truYum));
        
        string IMigrationMetadata.Id
        {
            get { return "202103010642565_truYum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
